
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: data_db
    ports:
      - "3306:3306"
    restart: always
    networks:
      - docker-atypon-network

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    restart: always
    networks:
      - docker-atypon-network

  enter-data-service:
    build: ./enter-data-service
    container_name: enter-data-service
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
      - authentication-service
    restart: always
    networks:
      - docker-atypon-network

  authentication-service:
    build: ./authentication-service
    container_name: authentication-service
    ports:
      - "5001:5001"
    restart: always
    networks:
      - docker-atypon-network

  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    ports:
      - "5002:5002"
    depends_on:
      - mysql-db
      - mongo-db
    restart: always
    networks:
      - docker-atypon-network

  show-results-service:
    build: ./show-results-service
    container_name: show-results-service
    ports:
      - "5003:5003"
    depends_on:
      - authentication-service
      - mongo-db
    restart: always
    networks:
      - docker-atypon-network

networks:
  docker-atypon-network: